# Generated by Django 5.0.7 on 2024-07-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="datetime",
            new_name="created_at",
        ),
    ]
