# Generated by Django 5.0.7 on 2024-07-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_datetime_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="checker",
            field=models.BooleanField(default=False),
        ),
    ]
