# Generated by Django 5.0.7 on 2024-07-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_task_checker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at", "-checker"]},
        ),
    ]
