# Generated by Django 5.0.7 on 2024-07-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["checker", "-created_at"]},
        ),
    ]
